export const SERVICES_AUTHENTICATE_AUTHENTICATION_PENDING =
  'SERVICES_AUTHENTICATE_AUTHENTICATION_PENDING';
export const SERVICES_AUTHENTICATE_AUTHENTICATION_FULFILLED =
  'SERVICES_AUTHENTICATE_AUTHENTICATION_FULFILLED';
export const SERVICES_AUTHENTICATE_AUTHENTICATION_REJECTED =
  'SERVICES_AUTHENTICATE_AUTHENTICATION_REJECTED';
export const SERVICES_AUTHENTICATE_LOGOUT = 'SERVICES_AUTHENTICATE_LOGOUT';
export const SHOPIFY_CONNECT_PENDING = 'SHOPIFY_CONNECT_PENDING';
export const SHOPIFY_CONNECT_FULFILLED = 'SHOPIFY_CONNECT_FULFILLED';
export const SHOPIFY_CONNECT_REJECTED = 'SHOPIFY_CONNECT_REJECTED';
export const FIND_PRODUCTS_PENDING = 'FIND_PRODUCTS_PENDING';
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCTS_SUCCESS';
export const FIND_PRODUCTS_ERROR = 'FIND_PRODUCTS_ERROR';
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
